
package com.stackroute.datastreamingservice.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import com.stackroute.datastreamingservice.model.User;
import com.stackroute.datastreamingservice.service.UserService;

import reactor.core.publisher.Flux;

@RestController
public class UserController {

	@Autowired
	UserService userService;

	/*
	 * This function returns the stream generated by the streaming service to other
	 * modules who make the API call to the given mapping
	 */

	@GetMapping(value = "/getUserData", produces = MediaType.APPLICATION_STREAM_JSON_VALUE)
	Flux<User> getUser() {
		return userService.getUserData();
	}

}
